### ISSUE TITLE
Difference to EcomDev

### ISSUE THREAD

**Issue by azngeek** [code-x/Xtest#5]
How exactly is this different to EcomDev_PHPUnit and what are the use cases where it makes more sense to use xtest? 

Regards

**Comment by tobi-pb** [comment]
In my opionion Ecomdev is made for module tests. You have to create all customer-data, products, configuration ec. before testing all functions of your module. 

xtest is made for integration tests. we use it to feel certain our shop is working well. because all data written is reverted after testing you could use your original dev-database for testing. you do not have to create customer-data, configuration or products first. just configure it and be sure your shop is working with your current products and configuration.

Additionally xtest provides a selenium integration with page objects for product-page, checkout ec. Finally my favorite feature for pure css/design testing using screenshots: create new user-account, automatticly login customer, create so orders using fixture and taking screenshots of customer account order grid :)
